image: crhym3/ci
git:
  depth: 1
script:
  # workaround for cache, see https://github.com/drone/drone/issues/147
  - mkdir -p /cache/node_modules
  - rm -rf node_modules
  - ln -s /cache/node_modules node_modules
  # install dependencies
  - npm -q install
  # ensure the build works
  # this will also run gulp test
  - gulp
cache:
  - /cache
