image: crhym3/ci
git:
  depth: 1
env:
  - DRONE_ACCOUNT=996714972814-7q585hf42vmouqkfdbccsnrc6jgclfm1@developer.gserviceaccount.com
script:
  # workaround for cache, see https://github.com/drone/drone/issues/147
  - mkdir -p /cache/node_modules
  - rm -rf node_modules
  - ln -s /cache/node_modules node_modules
  # install dependencies
  - npm install
  # ensure the build works
  # this will also run gulp test
  - gulp
  # publish to staging if this is master branch
  - if [ "$CI_BRANCH" != "master" ]; then exit 0; fi
  - apt-get install -y python-openssl
  - openssl aes-256-cbc -d -in .drone.p12.enc -out .drone.p12 -pass env:DRONE_PASS
  - /gcloud/bin/gcloud components update -q gsutil
  - /gcloud/bin/gcloud auth activate-service-account $DRONE_ACCOUNT --key-file .drone.p12
  - gulp publish:staging
cache:
  - /cache
