extends: google
globals:
  goog: false
env:
  browser: true
plugins:
  - mocha
parserOptions:
  ecmaVersion: 2015
  sourceType: module
rules:
  max-len: [error, 120]
  no-new: warn
  quotes: [error, single, {"avoidEscape": true}]
  no-var: error
  curly: error
  no-floating-decimal: error
  no-unused-vars: error
  # Disabling jsdoc rules for the time being, but should be discussed as to whether or not this is
  # something we should add in. For closure compatibility, we can investigate using something like
  # https://github.com/angular/tsickle with .dts files.
  require-jsdoc: off
  valid-jsdoc: off
  prefer-const: error

  # Rules for our mocha unit tests. Note that even though we use mocha, we model our unit tests
  # after frameworks such as tape and ava, which encourage modern paradigms, seek to minimize
  # shared state across tests, and try and make tests look as simple as possible.
  mocha/handle-done-callback: error
  mocha/no-exclusive-tests: error
  mocha/no-hooks: error
  mocha/no-identical-title: error
  mocha/no-nested-tests: error
  mocha/no-pending-tests: error
  mocha/no-skipped-tests: error
  mocha/valid-suite-description: [error, ^MDC.+]
