name: MDC Lint

on:
  push:
    branches:
      - master
      - develop
      - feature/**
    paths:
      - '**.js'
      - '**.ts'
      - '**.css'
      - '**.scss'
      - '**.html'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - run: npm i
      - run: npm run lint
